### ISSUE TITLE
il pulsante Iscriviti per gli appelli non funziona

### ISSUE THREAD

**Issue by WAPEETY** [epic-guys/Esse4#11]
forse é perché non ho compilato i questionari (in tal caso andrebbe segnato in qualche modo)

**Comment by WAPEETY** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.epic_guys.esse4.models.questionari.RigaLibrettoConStatoQuestionario$StatoQuestionario.ordinal()' on a null object reference
```

Also before any interaction:

```
 E  No adapter attached; skipping layout
```

**Comment by alvi-se** [comment]
L'iscrizione agli appelli non ha mai funzionato in realtà. Dato che la chiamata restituisce 500, ho pensato fosse colpa di Ess3 e me ne sono lavato le mani, fino a quando non ho scoperto che ci sono alcune ragioni client-side per cui restituisce 500 (ad esempio, JWT scaduto). Detto ciò, smanettando con la Insomnia, ho scoperto che l'iscrizione si può fare, bisogna solo capire il motivo per cui non va quella implementata nell'app.

A quanto pare comunque, 500 per Esse3 significa "cazzi tuoi a capire cosa hai sbagliato"

**Comment by WAPEETY** [comment]
HttpResponse<String> response = Unirest.post("https://esse3.unive.it/e3rest/api/calesa-service-v1/appelli/19/18181/41/iscritti")
  .header("Content-Type", "application/json")
  .header("User-Agent", "insomnia/8.5.1")
  .header("Authorization", "Bearer {{JWT_HERE}}")
  .body("{\n  \"adsceId\": 9850224\n}")
  .asString();

**Comment by WAPEETY** [comment]
fixed in e258ccf, finally
