### ISSUE TITLE
Si puó rimanere incastrati nell'app con una sessione scaduta e nessun modo per rinnovarla (a meno di chiuderla e riaprirla)

### ISSUE THREAD

**Issue by WAPEETY** [epic-guys/Esse4#12]
Basta fare il login e lasciare l'app aperta per 15 minuti (anche in background)

**Comment by alvi-se** [comment]
https://developer.android.com/topic/libraries/architecture/workmanager/

**Comment by WAPEETY** [comment]
done in [724facf](https://github.com/epic-guys/Esse4/commit/724facfeac9cbad99bae72c064c1a6ade90d44d7)
